disabled_rules:
   - trailing_whitespace
   - identifier_name
   
line_length:
    warning: 200
    error: 500
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
    ignores_enum_declarations: true
    
excluded:
  - DGCharts
